package net.uch.mapping;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import java.util.Set;
import net.uch.mapping.base.BaseTsSolicitudPersona;

/**
 * TsSolicitudPersona generated by MyEclipse Persistence Tools
 */
public class TsSolicitudPersona extends BaseTsSolicitudPersona{

	// Constructors

	/** default constructor */
	public TsSolicitudPersona() {
	}

	/** minimal constructor */
	public TsSolicitudPersona(Integer solperId) {
		super(solperId);
	}

	/** full constructor */
	public TsSolicitudPersona(Integer solperId, TsSolicitud tsSolicitud,
			Integer solperPersoId, String solperPersoTipo,
			String solperAprovada, Date solperFechaRegistro,
			Date solperFechaRevision, String solperActivo,
			String solperDescripcion, String solperObservacion, Set tsFuts, Date solperFechaAprovacion) {
		super(solperId, tsSolicitud, solperPersoId, solperPersoTipo,
				solperAprovada, solperFechaRegistro, solperFechaRevision,
				solperActivo, solperDescripcion, solperObservacion, tsFuts,solperFechaAprovacion);
	}

}
