package net.uch.mapping;

// Generated by MyEclipse Persistence Tools
import java.util.Date;
import net.uch.mapping.base.BaseClConsultaPublico;

/**
 * ClConsultaPublico generated by MyEclipse Persistence Tools
 */
public class ClConsultaPublico extends BaseClConsultaPublico implements
        java.io.Serializable {

    // Constructors
    /** default constructor */
    public ClConsultaPublico () {
    }

    public ClConsultaPublico ( Integer conId ) {
        super( conId );
    }

    /** full constructor */
    public ClConsultaPublico ( ClAlumno clAlumno, AcLocal acLocal, Integer areaId, Integer curId, String medId,String medIdCentros,String medIdPeriodicos, Integer detmedId,
            String conObservacionMedio, Date conFechaContacto,
            String conProcedencia, String conObservacionRegistro,
            Integer usuId, String conActivo, Integer plaId,
            String conEstadoMatricula, Date conFechaRegistro, String sConPrioridad, ClArbolAcademico clArbolAcademico, Integer espId,Integer matId ) {
        super( clAlumno, acLocal, areaId, curId, medId,medIdCentros,medIdPeriodicos, detmedId,
                conObservacionMedio, conFechaContacto, conProcedencia,
                conObservacionRegistro, usuId, conActivo, plaId,
                conEstadoMatricula, conFechaRegistro, sConPrioridad, clArbolAcademico, espId, matId );
    }
}
