package net.uch.mapping.base;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import net.uch.mapping.ClCurso;
import net.uch.mapping.ClTaller;

/**
 * AbstractClTallerAperturado generated by MyEclipse Persistence Tools
 */

public abstract class BaseClTallerAperturado implements
		java.io.Serializable {

	// Fields

	private Integer talapeId;
	private ClCurso clCurso;
	private ClTaller clTaller;
	private String talapeDescripcion;
	private Integer sisevaId;
	private Integer talapeNumHoras;
	private String talapeAperturado;
	private Date talapeFecha;
	private String talapeVigente;
	private String talapeActual;
	private String talapeActivo;
	private Set clSisEvaPersonalizados = new HashSet(0);
	private Set clSeccions = new HashSet(0);

	// Constructors

	/** default constructor */
	public BaseClTallerAperturado() {
	}

	/** minimal constructor */

        public BaseClTallerAperturado(Integer talapeId) {
            this.talapeId = talapeId;
	}
	public BaseClTallerAperturado(Integer talapeId, ClTaller clTaller) {
		this.talapeId = talapeId;
		this.clTaller = clTaller;
	}

	/** full constructor */
	public BaseClTallerAperturado(Integer talapeId, ClCurso clCurso,
			ClTaller clTaller, String talapeDescripcion, Integer sisevaId,
			Integer talapeNumHoras, String talapeAperturado, Date talapeFecha,
			String talapeVigente, String talapeActual, String talapeActivo,
			Set clSisEvaPersonalizados, Set clSeccions) {
		this.talapeId = talapeId;
		this.clCurso = clCurso;
		this.clTaller = clTaller;
		this.talapeDescripcion = talapeDescripcion;
		this.sisevaId = sisevaId;
		this.talapeNumHoras = talapeNumHoras;
		this.talapeAperturado = talapeAperturado;
		this.talapeFecha = talapeFecha;
		this.talapeVigente = talapeVigente;
		this.talapeActual = talapeActual;
		this.talapeActivo = talapeActivo;
		this.clSisEvaPersonalizados = clSisEvaPersonalizados;
		this.clSeccions = clSeccions;
	}

	// Property accessors

	public Integer getTalapeId() {
		return this.talapeId;
	}

	public void setTalapeId(Integer talapeId) {
		this.talapeId = talapeId;
	}

	public ClCurso getClCurso() {
		return this.clCurso;
	}

	public void setClCurso(ClCurso clCurso) {
		this.clCurso = clCurso;
	}

	public ClTaller getClTaller() {
		return this.clTaller;
	}

	public void setClTaller(ClTaller clTaller) {
		this.clTaller = clTaller;
	}

	public String getTalapeDescripcion() {
		return this.talapeDescripcion;
	}

	public void setTalapeDescripcion(String talapeDescripcion) {
		this.talapeDescripcion = talapeDescripcion;
	}

	public Integer getSisevaId() {
		return this.sisevaId;
	}

	public void setSisevaId(Integer sisevaId) {
		this.sisevaId = sisevaId;
	}

	public Integer getTalapeNumHoras() {
		return this.talapeNumHoras;
	}

	public void setTalapeNumHoras(Integer talapeNumHoras) {
		this.talapeNumHoras = talapeNumHoras;
	}

	public String getTalapeAperturado() {
		return this.talapeAperturado;
	}

	public void setTalapeAperturado(String talapeAperturado) {
		this.talapeAperturado = talapeAperturado;
	}

	public Date getTalapeFecha() {
		return this.talapeFecha;
	}

	public void setTalapeFecha(Date talapeFecha) {
		this.talapeFecha = talapeFecha;
	}

	public String getTalapeVigente() {
		return this.talapeVigente;
	}

	public void setTalapeVigente(String talapeVigente) {
		this.talapeVigente = talapeVigente;
	}

	public String getTalapeActual() {
		return this.talapeActual;
	}

	public void setTalapeActual(String talapeActual) {
		this.talapeActual = talapeActual;
	}

	public String getTalapeActivo() {
		return this.talapeActivo;
	}

	public void setTalapeActivo(String talapeActivo) {
		this.talapeActivo = talapeActivo;
	}

	public Set getClSisEvaPersonalizados() {
		return this.clSisEvaPersonalizados;
	}

	public void setClSisEvaPersonalizados(Set clSisEvaPersonalizados) {
		this.clSisEvaPersonalizados = clSisEvaPersonalizados;
	}

	public Set getClSeccions() {
		return this.clSeccions;
	}

	public void setClSeccions(Set clSeccions) {
		this.clSeccions = clSeccions;
	}
}