package net.uch.mapping;
// Generated 14/02/2011 09:37:59 AM by Hibernate Tools 3.2.1.GA

/**
 * TbParametroReportes generated by hbm2java
 */
public class TbParametroReportes implements java.io.Serializable {

    private Integer parRepId;
    private TbReporte tbReporte;
    private String parRepParametroRepor;
    private Integer parRepTipDatId;
    private String parRepParametroInter;
    private Integer parRepRequerido;

    public TbParametroReportes() {
    }

    public TbParametroReportes( TbReporte tbReporte, String parRepParametroRepor, Integer parRepTipDatId, String parRepParametroInter ) {
        this.tbReporte = tbReporte;
        this.parRepParametroRepor = parRepParametroRepor;
        this.parRepTipDatId = parRepTipDatId;
        this.parRepParametroInter = parRepParametroInter;
    }

    public Integer getParRepRequerido() {
        return parRepRequerido;
    }

    public void setParRepRequerido( Integer parRepRequerido ) {
        this.parRepRequerido = parRepRequerido;
    }

    public Integer getParRepId() {
        return this.parRepId;
    }

    public void setParRepId( Integer parRepId ) {
        this.parRepId = parRepId;
    }

    public TbReporte getTbReporte() {
        return this.tbReporte;
    }

    public void setTbReporte( TbReporte tbReporte ) {
        this.tbReporte = tbReporte;
    }

    public String getParRepParametroRepor() {
        return this.parRepParametroRepor;
    }

    public void setParRepParametroRepor( String parRepParametroRepor ) {
        this.parRepParametroRepor = parRepParametroRepor;
    }

    public Integer getParRepTipDatId() {
        return this.parRepTipDatId;
    }

    public void setParRepTipDatId( Integer parRepTipDatId ) {
        this.parRepTipDatId = parRepTipDatId;
    }

    public String getParRepParametroInter() {
        return this.parRepParametroInter;
    }

    public void setParRepParametroInter( String parRepParametroInter ) {
        this.parRepParametroInter = parRepParametroInter;
    }
}
