package net.uch.mapping;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import net.uch.mapping.base.BaseAcAlumnoEstado;

/**
 * AcAlumnoEstado generated by MyEclipse Persistence Tools
 */
public class AcAlumnoEstado extends BaseAcAlumnoEstado implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public AcAlumnoEstado() {
	}

	/** full constructor */
	public AcAlumnoEstado(AcAlumno acAlumno, AcSemestre acSemestre,
			String aluestEstado, String aluestResolucion,
			String aluestObservacion, String aluestActivo, Date aluestRegistro,
			Integer aluestPeriodos, String semIds) {
		super(acAlumno, acSemestre, aluestEstado, aluestResolucion,
				aluestObservacion, aluestActivo, aluestRegistro, aluestPeriodos,semIds);
	}

}
