package net.uch.mapping;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import java.util.Set;
import net.uch.mapping.base.BaseClTallerAperturado;

/**
 * ClTallerAperturado generated by MyEclipse Persistence Tools
 */
public class ClTallerAperturado extends BaseClTallerAperturado implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public ClTallerAperturado() {
	}

	/** minimal constructor */
	public ClTallerAperturado(Integer talapeId, ClTaller clTaller) {
		super(talapeId, clTaller);
	}

        public ClTallerAperturado(Integer talapeId) {
		super(talapeId);
	}

	/** full constructor */
	public ClTallerAperturado(Integer talapeId, ClCurso clCurso,
			ClTaller clTaller, String talapeDescripcion, Integer sisevaId,
			Integer talapeNumHoras, String talapeAperturado, Date talapeFecha,
			String talapeVigente, String talapeActual, String talapeActivo,
			Set clSisEvaPersonalizados, Set clSeccions) {
		super(talapeId, clCurso, clTaller, talapeDescripcion, sisevaId,
				talapeNumHoras, talapeAperturado, talapeFecha, talapeVigente,
				talapeActual, talapeActivo, clSisEvaPersonalizados, clSeccions);
	}

}
