package net.uch.mapping;

// Generated by MyEclipse Persistence Tools
import java.util.Set;
import net.uch.mapping.base.BaseTbMenu;

/**
 * TbMenu generated by MyEclipse Persistence Tools
 */
public class TbMenu extends BaseTbMenu implements java.io.Serializable {

    // Constructors
    /** default constructor */
    public TbMenu() {
    }

    /** minimal constructor */
    public TbMenu(Integer menId) {
        super(menId);
    }

    /** full constructor */
    public TbMenu(Integer menId, String menCodigo, String menDescripcion,
            String menOpc, String menAccion, String menActivo, Integer menIdPadre, Set tbMenuRols) {
        super(menId, menCodigo, menDescripcion, menOpc,
                menAccion, menActivo, menIdPadre, tbMenuRols);
    }
}
