package net.uch.mapping.base;

/**
 * AbstractTbAlumnoFicha generated by MyEclipse Persistence Tools
 */

public abstract class BaseTbAlumnoFicha implements java.io.Serializable {

	// Fields

	private Integer ficId;
	private Integer aluId;
	private String ficActivo;

	// Constructors

	/** default constructor */
	public BaseTbAlumnoFicha() {
	}

	/** minimal constructor */
	public BaseTbAlumnoFicha(Integer ficId) {
		this.ficId = ficId;
	}

	/** full constructor */
	public BaseTbAlumnoFicha(Integer ficId, Integer aluId, String ficActivo) {
		this.ficId = ficId;
		this.aluId = aluId;
		this.ficActivo = ficActivo;
	}

	// Property accessors

	public Integer getFicId() {
		return this.ficId;
	}

	public void setFicId(Integer ficId) {
		this.ficId = ficId;
	}

	public Integer getAluId() {
		return this.aluId;
	}

	public void setAluId(Integer aluId) {
		this.aluId = aluId;
	}

	public String getFicActivo() {
		return this.ficActivo;
	}

	public void setFicActivo(String ficActivo) {
		this.ficActivo = ficActivo;
	}

}