package net.uch.mapping.base;

import java.util.Date;
import java.util.Set;
import net.uch.mapping.AcAlumno;
import net.uch.mapping.AcEstadoSemestre;
import net.uch.mapping.AcSemestre;

/**
 * AbstractAcAlumnoEstado generated by MyEclipse Persistence Tools
 */

public abstract class BaseAcAlumnoEstado implements java.io.Serializable {

	// Fields

	private Integer aluestId;
	private AcAlumno acAlumno;
	private AcSemestre acSemestre;
	private String aluestEstado;
	private String aluestResolucion;
	private String aluestObservacion;
	private String aluestActivo;
	private Date aluestRegistro;
	private Integer aluestPeriodos;
        private AcSemestre acSemestreBak;
        private String semIds;
        
        private Set<AcEstadoSemestre> acEstadoSemestres;

	// Constructors

	/** default constructor */
	public BaseAcAlumnoEstado() {
	}

	/** full constructor */
	public BaseAcAlumnoEstado(AcAlumno acAlumno, AcSemestre acSemestre,
			String aluestEstado, String aluestResolucion,
			String aluestObservacion, String aluestActivo, Date aluestRegistro,
			Integer aluestPeriodos, String semIds) {
		this.acAlumno = acAlumno;
		this.acSemestre = acSemestre;
		this.aluestEstado = aluestEstado;
		this.aluestResolucion = aluestResolucion;
		this.aluestObservacion = aluestObservacion;
		this.aluestActivo = aluestActivo;
		this.aluestRegistro = aluestRegistro;
		this.aluestPeriodos = aluestPeriodos;
                this.semIds=semIds;
	}

	// Property accessors

	public Integer getAluestId() {
		return this.aluestId;
	}

	public void setAluestId(Integer aluestId) {
		this.aluestId = aluestId;
	}

	public AcAlumno getAcAlumno() {
		return this.acAlumno;
	}

	public void setAcAlumno(AcAlumno acAlumno) {
		this.acAlumno = acAlumno;
	}

	public AcSemestre getAcSemestre() {
		return this.acSemestre;
	}

	public void setAcSemestre(AcSemestre acSemestre) {
		this.acSemestre = acSemestre;
	}

	public String getAluestEstado() {
		return this.aluestEstado;
	}

	public void setAluestEstado(String aluestEstado) {
		this.aluestEstado = aluestEstado;
	}

	public String getAluestResolucion() {
		return this.aluestResolucion;
	}

	public void setAluestResolucion(String aluestResolucion) {
		this.aluestResolucion = aluestResolucion;
	}

	public String getAluestObservacion() {
		return this.aluestObservacion;
	}

	public void setAluestObservacion(String aluestObservacion) {
		this.aluestObservacion = aluestObservacion;
	}

	public String getAluestActivo() {
		return this.aluestActivo;
	}

	public void setAluestActivo(String aluestActivo) {
		this.aluestActivo = aluestActivo;
	}

	public Date getAluestRegistro() {
		return this.aluestRegistro;
	}

	public void setAluestRegistro(Date aluestRegistro) {
		this.aluestRegistro = aluestRegistro;
	}

	public Integer getAluestPeriodos() {
		return this.aluestPeriodos;
	}

	public void setAluestPeriodos(Integer aluestPeriodos) {
		this.aluestPeriodos = aluestPeriodos;
	}

    public AcSemestre getAcSemestreBak() {
        return acSemestreBak;
    }

    public void setAcSemestreBak(AcSemestre acSemestreBak) {
        this.acSemestreBak = acSemestreBak;
    }

    public String getSemIds() {
        return semIds;
    }

    public void setSemIds(String semIds) {
        this.semIds = semIds;
    }

    public Set<AcEstadoSemestre> getAcEstadoSemestres() {
        return acEstadoSemestres;
    }

    public void setAcEstadoSemestres(Set<AcEstadoSemestre> acEstadoSemestres) {
        this.acEstadoSemestres = acEstadoSemestres;
    }
    
    
        

}