package net.uch.mapping.base;

import java.io.Serializable;
import net.uch.mapping.AcEspecialidad;

/**
 * AbstractAcSeccionEspecialidad generated by MyEclipse Persistence Tools
 */

public abstract class BaseAcSeccionEspecialidad implements Serializable {

	// Fields

	private Integer secespId;
	private AcEspecialidad acEspecialidad;
	private String secespCodigo;
	private String secespNombre;
	private String secespCiclo;
	private String secespActivo;

	// Constructors

	/** default constructor */
	public BaseAcSeccionEspecialidad() {
	}

	/** minimal constructor */
	public BaseAcSeccionEspecialidad(Integer secespId) {
		this.secespId = secespId;
	}

	/** full constructor */
	public BaseAcSeccionEspecialidad(Integer secespId,
			AcEspecialidad acEspecialidad, String secespCodigo,
			String secespNombre, String secespCiclo, String secespActivo) {
		this.secespId = secespId;
		this.acEspecialidad = acEspecialidad;
		this.secespCodigo = secespCodigo;
		this.secespNombre = secespNombre;
		this.secespCiclo = secespCiclo;
		this.secespActivo = secespActivo;
	}

	// Property accessors

	public Integer getSecespId() {
		return this.secespId;
	}

	public void setSecespId(Integer secespId) {
		this.secespId = secespId;
	}

	public AcEspecialidad getAcEspecialidad() {
		return this.acEspecialidad;
	}

	public void setAcEspecialidad(AcEspecialidad acEspecialidad) {
		this.acEspecialidad = acEspecialidad;
	}

	public String getSecespCodigo() {
		return this.secespCodigo;
	}

	public void setSecespCodigo(String secespCodigo) {
		this.secespCodigo = secespCodigo;
	}

	public String getSecespNombre() {
		return this.secespNombre;
	}

	public void setSecespNombre(String secespNombre) {
		this.secespNombre = secespNombre;
	}

	public String getSecespCiclo() {
		return this.secespCiclo;
	}

	public void setSecespCiclo(String secespCiclo) {
		this.secespCiclo = secespCiclo;
	}

	public String getSecespActivo() {
		return this.secespActivo;
	}

	public void setSecespActivo(String secespActivo) {
		this.secespActivo = secespActivo;
	}

}