package net.uch.mapping.base;

import java.util.Date;
import net.uch.mapping.AcAlumno;
import net.uch.mapping.AcTurno;

/**
 * AbstractTbIncidenciaLab generated by MyEclipse Persistence Tools
 */
public abstract class BaseTbIncidenciaLab implements java.io.Serializable {

    // Fields
    private Integer inclabId;
    private AcAlumno acAlumno;
    private String inclabCicloAlu;
    private Integer curId;
    private Integer secId;
    private String inclabEquipo;
    private String inclabDescripcionDanio;
    private String inclabActivo;
    private String inclabEstado;
    private String tipoIncidencia;
    private Date inclabFechaRegistro;
    private AcTurno acTurno;

    // Constructors
    /**
     * default constructor
     */
    public BaseTbIncidenciaLab() {
    }

    public BaseTbIncidenciaLab(Integer inclabId) {
        this.inclabId = inclabId;
    }

    /**
     * full constructor
     */
    public BaseTbIncidenciaLab(AcAlumno acAlumno, String inclabCicloAlu,
            Integer curId, Integer secId,
            String inclabEquipo, String inclabDescripcionDanio,
            String inclabActivo, String inclabEstado, AcTurno acTurno) {
        this.acAlumno = acAlumno;
        this.inclabCicloAlu = inclabCicloAlu;
        this.curId = curId;
        this.secId = secId;
        this.inclabEquipo = inclabEquipo;
        this.inclabDescripcionDanio = inclabDescripcionDanio;
        this.inclabActivo = inclabActivo;
        this.inclabEstado = inclabEstado;
        this.acTurno = acTurno;
    }

    // Property accessors
    public Integer getInclabId() {
        return this.inclabId;
    }

    public void setInclabId(Integer inclabId) {
        this.inclabId = inclabId;
    }

    public AcAlumno getAcAlumno() {
        return this.acAlumno;
    }

    public void setAcAlumno(AcAlumno acAlumno) {
        this.acAlumno = acAlumno;
    }

    public String getInclabCicloAlu() {
        return this.inclabCicloAlu;
    }

    public void setInclabCicloAlu(String inclabCicloAlu) {
        this.inclabCicloAlu = inclabCicloAlu;
    }

    public Integer getCurId() {
        return this.curId;
    }

    public void setCurId(Integer curId) {
        this.curId = curId;
    }

    public Integer getSecId() {
        return this.secId;
    }

    public void setSecId(Integer secId) {
        this.secId = secId;
    }

    public String getInclabEquipo() {
        return this.inclabEquipo;
    }

    public void setInclabEquipo(String inclabEquipo) {
        this.inclabEquipo = inclabEquipo;
    }

    public String getInclabDescripcionDanio() {
        return this.inclabDescripcionDanio;
    }

    public void setInclabDescripcionDanio(String inclabDescripcionDanio) {
        this.inclabDescripcionDanio = inclabDescripcionDanio;
    }

    public String getInclabActivo() {
        return this.inclabActivo;
    }

    public void setInclabActivo(String inclabActivo) {
        this.inclabActivo = inclabActivo;
    }

    public String getInclabEstado() {
        return inclabEstado;
    }

    public void setInclabEstado(String inclabEstado) {
        this.inclabEstado = inclabEstado;
    }

    public AcTurno getAcTurno() {
        return acTurno;
    }

    public void setAcTurno(AcTurno acTurno) {
        this.acTurno = acTurno;
    }

    public String getTipoIncidencia() {
        return tipoIncidencia;
    }

    public void setTipoIncidencia(String tipoIncidencia) {
        this.tipoIncidencia = tipoIncidencia;
    }

    public Date getInclabFechaRegistro() {
        return inclabFechaRegistro;
    }

    public void setInclabFechaRegistro(Date inclabFechaRegistro) {
        this.inclabFechaRegistro = inclabFechaRegistro;
    }
}