package net.uch.mapping.base;

import java.util.Date;
import net.uch.mapping.ClPlantillaHorario;

/**
 * AbstractClPlantillaHorarioDet generated by MyEclipse Persistence Tools
 */

public abstract class BaseClPlantillaHorarioDet implements
		java.io.Serializable {

	// Fields

	private Integer pladetId;
	private ClPlantillaHorario clPlantillaHorario;
	private String pladetDia;
	private Date paldetHoraIni;
	private Date pladetHoraFin;
	private String pladetTipo;
	private String pladetActivo;

	// Constructors

	/** default constructor */
	public BaseClPlantillaHorarioDet() {
	}

	/** minimal constructor */
	public BaseClPlantillaHorarioDet(Integer pladetId) {
		this.pladetId = pladetId;
	}

	/** full constructor */
	public BaseClPlantillaHorarioDet(Integer pladetId,
			ClPlantillaHorario clPlantillaHorario, String pladetDia,
			Date paldetHoraIni, Date pladetHoraFin, String pladetTipo,
			String pladetActivo) {
		this.pladetId = pladetId;
		this.clPlantillaHorario = clPlantillaHorario;
		this.pladetDia = pladetDia;
		this.paldetHoraIni = paldetHoraIni;
		this.pladetHoraFin = pladetHoraFin;
		this.pladetTipo = pladetTipo;
		this.pladetActivo = pladetActivo;
	}

	// Property accessors

	public Integer getPladetId() {
		return this.pladetId;
	}

	public void setPladetId(Integer pladetId) {
		this.pladetId = pladetId;
	}

	public ClPlantillaHorario getClPlantillaHorario() {
		return this.clPlantillaHorario;
	}

	public void setClPlantillaHorario(ClPlantillaHorario clPlantillaHorario) {
		this.clPlantillaHorario = clPlantillaHorario;
	}

	public String getPladetDia() {
		return this.pladetDia;
	}

	public void setPladetDia(String pladetDia) {
		this.pladetDia = pladetDia;
	}

	public Date getPaldetHoraIni() {
		return this.paldetHoraIni;
	}

	public void setPaldetHoraIni(Date paldetHoraIni) {
		this.paldetHoraIni = paldetHoraIni;
	}

	public Date getPladetHoraFin() {
		return this.pladetHoraFin;
	}

	public void setPladetHoraFin(Date pladetHoraFin) {
		this.pladetHoraFin = pladetHoraFin;
	}

	public String getPladetTipo() {
		return this.pladetTipo;
	}

	public void setPladetTipo(String pladetTipo) {
		this.pladetTipo = pladetTipo;
	}

	public String getPladetActivo() {
		return this.pladetActivo;
	}

	public void setPladetActivo(String pladetActivo) {
		this.pladetActivo = pladetActivo;
	}

}