package net.uch.mapping.base;

import java.util.HashSet;
import java.util.Set;
import net.uch.mapping.ClModulo;
import net.uch.mapping.ClPlancurricular;

/**
 * AbstractClTaller generated by MyEclipse Persistence Tools
 */

public abstract class BaseClTaller implements java.io.Serializable {

	// Fields

	private Integer talId;
	private ClModulo clModulo;
	private ClPlancurricular clPlancurricular;
	private String talCodigo;
	private String talDescripcion;
	private String talNumero;
	private Integer curId;
	private String talActivo;
	private Set clPreRequisitosesForTalIdRequisito = new HashSet(0);
	private Set clPreRequisitosesForTalId = new HashSet(0);
	private Set clInicios = new HashSet(0);
	private Set clTallerAperturados = new HashSet(0);

	// Constructors

	/** default constructor */
	public BaseClTaller() {
	}

	/** minimal constructor */
	public BaseClTaller(Integer talId, ClPlancurricular clPlancurricular,
			Integer curId) {
		this.talId = talId;
		this.clPlancurricular = clPlancurricular;
		this.curId = curId;
	}

	/** full constructor */
	public BaseClTaller(Integer talId, ClModulo clModulo,
			ClPlancurricular clPlancurricular, String talCodigo,
			String talDescripcion, String talNumero, Integer curId,
			String talActivo, Set clPreRequisitosesForTalIdRequisito,
			Set clPreRequisitosesForTalId, Set clInicios,
			Set clTallerAperturados) {
		this.talId = talId;
		this.clModulo = clModulo;
		this.clPlancurricular = clPlancurricular;
		this.talCodigo = talCodigo;
		this.talDescripcion = talDescripcion;
		this.talNumero = talNumero;
		this.curId = curId;
		this.talActivo = talActivo;
		this.clPreRequisitosesForTalIdRequisito = clPreRequisitosesForTalIdRequisito;
		this.clPreRequisitosesForTalId = clPreRequisitosesForTalId;
		this.clInicios = clInicios;
		this.clTallerAperturados = clTallerAperturados;
	}

	// Property accessors

	public Integer getTalId() {
		return this.talId;
	}

	public void setTalId(Integer talId) {
		this.talId = talId;
	}

	public ClModulo getClModulo() {
		return this.clModulo;
	}

	public void setClModulo(ClModulo clModulo) {
		this.clModulo = clModulo;
	}

	public ClPlancurricular getClPlancurricular() {
		return this.clPlancurricular;
	}

	public void setClPlancurricular(ClPlancurricular clPlancurricular) {
		this.clPlancurricular = clPlancurricular;
	}

	public String getTalCodigo() {
		return this.talCodigo;
	}

	public void setTalCodigo(String talCodigo) {
		this.talCodigo = talCodigo;
	}

	public String getTalDescripcion() {
		return this.talDescripcion;
	}

	public void setTalDescripcion(String talDescripcion) {
		this.talDescripcion = talDescripcion;
	}

	public String getTalNumero() {
		return this.talNumero;
	}

	public void setTalNumero(String talNumero) {
		this.talNumero = talNumero;
	}

	public Integer getCurId() {
		return this.curId;
	}

	public void setCurId(Integer curId) {
		this.curId = curId;
	}

	public String getTalActivo() {
		return this.talActivo;
	}

	public void setTalActivo(String talActivo) {
		this.talActivo = talActivo;
	}

	public Set getClPreRequisitosesForTalIdRequisito() {
		return this.clPreRequisitosesForTalIdRequisito;
	}

	public void setClPreRequisitosesForTalIdRequisito(
			Set clPreRequisitosesForTalIdRequisito) {
		this.clPreRequisitosesForTalIdRequisito = clPreRequisitosesForTalIdRequisito;
	}

	public Set getClPreRequisitosesForTalId() {
		return this.clPreRequisitosesForTalId;
	}

	public void setClPreRequisitosesForTalId(Set clPreRequisitosesForTalId) {
		this.clPreRequisitosesForTalId = clPreRequisitosesForTalId;
	}

	public Set getClInicios() {
		return this.clInicios;
	}

	public void setClInicios(Set clInicios) {
		this.clInicios = clInicios;
	}

	public Set getClTallerAperturados() {
		return this.clTallerAperturados;
	}

	public void setClTallerAperturados(Set clTallerAperturados) {
		this.clTallerAperturados = clTallerAperturados;
	}

}