package net.uch.mapping.base;

import net.uch.mapping.ClMedioPublicidad;

/**
 * AbstractClMedioPublicidadDet generated by MyEclipse Persistence Tools
 */

public abstract class BaseClMedioPublicidadDet implements
		java.io.Serializable {

	// Fields

	private Integer idPubDet;
	private ClMedioPublicidad clMedioPublicidad;
	private String pubDetDes;
	private String pubDetEst;
	private Integer pubDetOrd;

	// Constructors

	/** default constructor */
	public BaseClMedioPublicidadDet() {
	}

	/** minimal constructor */
	public BaseClMedioPublicidadDet(Integer idPubDet) {
		this.idPubDet = idPubDet;
	}

	/** full constructor */
	public BaseClMedioPublicidadDet(Integer idPubDet,
			ClMedioPublicidad clMedioPublicidad, String pubDetDes,
			String pubDetEst, Integer pubDetOrd) {
		this.idPubDet = idPubDet;
		this.clMedioPublicidad = clMedioPublicidad;
		this.pubDetDes = pubDetDes;
		this.pubDetEst = pubDetEst;
		this.pubDetOrd = pubDetOrd;
	}

	// Property accessors

	public Integer getIdPubDet() {
		return this.idPubDet;
	}

	public void setIdPubDet(Integer idPubDet) {
		this.idPubDet = idPubDet;
	}

	public ClMedioPublicidad getClMedioPublicidad() {
		return this.clMedioPublicidad;
	}

	public void setClMedioPublicidad(ClMedioPublicidad clMedioPublicidad) {
		this.clMedioPublicidad = clMedioPublicidad;
	}

	public String getPubDetDes() {
		return this.pubDetDes;
	}

	public void setPubDetDes(String pubDetDes) {
		this.pubDetDes = pubDetDes;
	}

	public String getPubDetEst() {
		return this.pubDetEst;
	}

	public void setPubDetEst(String pubDetEst) {
		this.pubDetEst = pubDetEst;
	}

	public Integer getPubDetOrd() {
		return this.pubDetOrd;
	}

	public void setPubDetOrd(Integer pubDetOrd) {
		this.pubDetOrd = pubDetOrd;
	}

}