package net.uch.mapping.base;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AbstractClPlantillaHorario generated by MyEclipse Persistence Tools
 */

public abstract class BaseClPlantillaHorario implements
		java.io.Serializable {

	// Fields

	private Integer plaId;
	private String plaDescripcion;
	private Date plaFechaCreacion;
	private String palTurno;
	private Integer usuId;
	private String plaActivo;
	private Set clPlantillaHorarioDets = new HashSet(0);

	// Constructors

	/** default constructor */
	public BaseClPlantillaHorario() {
	}

	/** minimal constructor */
	public BaseClPlantillaHorario(Integer plaId) {
		this.plaId = plaId;
	}

	/** full constructor */
	public BaseClPlantillaHorario(Integer plaId, String plaDescripcion,
			Date plaFechaCreacion, String palTurno, Integer usuId,
			String plaActivo, Set clPlantillaHorarioDets) {
		this.plaId = plaId;
		this.plaDescripcion = plaDescripcion;
		this.plaFechaCreacion = plaFechaCreacion;
		this.palTurno = palTurno;
		this.usuId = usuId;
		this.plaActivo = plaActivo;
		this.clPlantillaHorarioDets = clPlantillaHorarioDets;
	}

	// Property accessors

	public Integer getPlaId() {
		return this.plaId;
	}

	public void setPlaId(Integer plaId) {
		this.plaId = plaId;
	}

	public String getPlaDescripcion() {
		return this.plaDescripcion;
	}

	public void setPlaDescripcion(String plaDescripcion) {
		this.plaDescripcion = plaDescripcion;
	}

	public Date getPlaFechaCreacion() {
		return this.plaFechaCreacion;
	}

	public void setPlaFechaCreacion(Date plaFechaCreacion) {
		this.plaFechaCreacion = plaFechaCreacion;
	}

	public String getPalTurno() {
		return this.palTurno;
	}

	public void setPalTurno(String palTurno) {
		this.palTurno = palTurno;
	}

	public Integer getUsuId() {
		return this.usuId;
	}

	public void setUsuId(Integer usuId) {
		this.usuId = usuId;
	}

	public String getPlaActivo() {
		return this.plaActivo;
	}

	public void setPlaActivo(String plaActivo) {
		this.plaActivo = plaActivo;
	}

	public Set getClPlantillaHorarioDets() {
		return this.clPlantillaHorarioDets;
	}

	public void setClPlantillaHorarioDets(Set clPlantillaHorarioDets) {
		this.clPlantillaHorarioDets = clPlantillaHorarioDets;
	}

}