package net.uch.mapping.base;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import net.uch.mapping.AcLocal;
import net.uch.mapping.ClArbolAcademico;

/**
 * AbstractClInicio generated by MyEclipse Persistence Tools
 */

public abstract class BaseClInicio implements java.io.Serializable {

	// Fields

	private Integer iniId;
	private ClArbolAcademico clArbolAcademico;
	private AcLocal acLocal;
	private String iniCodigo;
	private String iniDescripcion;
	private String iniTurno;
	private Date iniFechaInicio;
	private Date iniFechaFin;
	private String iniAperturado;
	private String iniActivo;
	private String iniResolucion;
	private Integer iniNroHoras;
	private Set clSeccions = new HashSet(0);

	// Constructors

	/** default constructor */
	public BaseClInicio() {
	}

	/** minimal constructor */
	public BaseClInicio(Integer iniId) {
		this.iniId = iniId;
	}

	/** full constructor */
	public BaseClInicio(Integer iniId, ClArbolAcademico clArbolAcademico,
			AcLocal acLocal, String iniCodigo, String iniDescripcion,
			String iniTurno, Date iniFechaInicio, Date iniFechaFin,
			String iniAperturado, String iniActivo, String iniResolucion,
			Integer iniNroHoras, Set clSeccions) {
		this.iniId = iniId;
		this.clArbolAcademico = clArbolAcademico;
		this.acLocal = acLocal;
		this.iniCodigo = iniCodigo;
		this.iniDescripcion = iniDescripcion;
		this.iniTurno = iniTurno;
		this.iniFechaInicio = iniFechaInicio;
		this.iniFechaFin = iniFechaFin;
		this.iniAperturado = iniAperturado;
		this.iniActivo = iniActivo;
		this.iniResolucion = iniResolucion;
		this.iniNroHoras = iniNroHoras;
		this.clSeccions = clSeccions;
	}

	// Property accessors

	public Integer getIniId() {
		return this.iniId;
	}

	public void setIniId(Integer iniId) {
		this.iniId = iniId;
	}

	public ClArbolAcademico getClArbolAcademico() {
		return this.clArbolAcademico;
	}

	public void setClArbolAcademico(ClArbolAcademico clArbolAcademico) {
		this.clArbolAcademico = clArbolAcademico;
	}

	public AcLocal getAcLocal() {
		return this.acLocal;
	}

	public void setAcLocal(AcLocal acLocal) {
		this.acLocal = acLocal;
	}

	public String getIniCodigo() {
		return this.iniCodigo;
	}

	public void setIniCodigo(String iniCodigo) {
		this.iniCodigo = iniCodigo;
	}

	public String getIniDescripcion() {
		return this.iniDescripcion;
	}

	public void setIniDescripcion(String iniDescripcion) {
		this.iniDescripcion = iniDescripcion;
	}

	public String getIniTurno() {
		return this.iniTurno;
	}

	public void setIniTurno(String iniTurno) {
		this.iniTurno = iniTurno;
	}

	public Date getIniFechaInicio() {
		return this.iniFechaInicio;
	}

	public void setIniFechaInicio(Date iniFechaInicio) {
		this.iniFechaInicio = iniFechaInicio;
	}

	public Date getIniFechaFin() {
		return this.iniFechaFin;
	}

	public void setIniFechaFin(Date iniFechaFin) {
		this.iniFechaFin = iniFechaFin;
	}

	public String getIniAperturado() {
		return this.iniAperturado;
	}

	public void setIniAperturado(String iniAperturado) {
		this.iniAperturado = iniAperturado;
	}

	public String getIniActivo() {
		return this.iniActivo;
	}

	public void setIniActivo(String iniActivo) {
		this.iniActivo = iniActivo;
	}

	public String getIniResolucion() {
		return this.iniResolucion;
	}

	public void setIniResolucion(String iniResolucion) {
		this.iniResolucion = iniResolucion;
	}

	public Integer getIniNroHoras() {
		return this.iniNroHoras;
	}

	public void setIniNroHoras(Integer iniNroHoras) {
		this.iniNroHoras = iniNroHoras;
	}

	public Set getClSeccions() {
		return this.clSeccions;
	}

	public void setClSeccions(Set clSeccions) {
		this.clSeccions = clSeccions;
	}

}