package net.uch.mapping.base;

import java.util.HashSet;
import java.util.Set;

/**
 * AbstractAdAreaInstitucion generated by MyEclipse Persistence Tools
 */

public abstract class BaseAdAreaInstitucion implements java.io.Serializable {

	// Fields

	private Integer areinsId;
	private String areinsCodigo;
	private String areinsDescripcion;
	private String areinsTipo;
	private String areinsActivo;
	private Set tsSolicituds = new HashSet(0);

	// Constructors

	/** default constructor */
	public BaseAdAreaInstitucion() {
	}

	/** minimal constructor */
	public BaseAdAreaInstitucion(Integer areinsId) {
		this.areinsId = areinsId;
	}

	/** full constructor */
	public BaseAdAreaInstitucion(Integer areinsId, String areinsCodigo,
			String areinsDescripcion, String areinsTipo, String areinsActivo,
			Set tsSolicituds) {
		this.areinsId = areinsId;
		this.areinsCodigo = areinsCodigo;
		this.areinsDescripcion = areinsDescripcion;
		this.areinsTipo = areinsTipo;
		this.areinsActivo = areinsActivo;
		this.tsSolicituds = tsSolicituds;
	}

	// Property accessors

	public Integer getAreinsId() {
		return this.areinsId;
	}

	public void setAreinsId(Integer areinsId) {
		this.areinsId = areinsId;
	}

	public String getAreinsCodigo() {
		return this.areinsCodigo;
	}

	public void setAreinsCodigo(String areinsCodigo) {
		this.areinsCodigo = areinsCodigo;
	}

	public String getAreinsDescripcion() {
		return this.areinsDescripcion;
	}

	public void setAreinsDescripcion(String areinsDescripcion) {
		this.areinsDescripcion = areinsDescripcion;
	}

	public String getAreinsTipo() {
		return this.areinsTipo;
	}

	public void setAreinsTipo(String areinsTipo) {
		this.areinsTipo = areinsTipo;
	}

	public String getAreinsActivo() {
		return this.areinsActivo;
	}

	public void setAreinsActivo(String areinsActivo) {
		this.areinsActivo = areinsActivo;
	}

	public Set getTsSolicituds() {
		return this.tsSolicituds;
	}

	public void setTsSolicituds(Set tsSolicituds) {
		this.tsSolicituds = tsSolicituds;
	}

}