package net.uch.mapping.base;

import java.util.Date;
import net.uch.mapping.ClConsultaPublico;

/**
 * AbstractClPublicoConsultaDetalle generated by MyEclipse Persistence Tools
 */

public abstract class BaseClPublicoConsultaDetalle implements
		java.io.Serializable {

	// Fields

	private Integer consultaDetalleId;
	private ClConsultaPublico clPublicoConsulta;
	private String observacion;
	private Date fecha;

	// Constructors

	/** default constructor */
	public BaseClPublicoConsultaDetalle() {
	}

	/** minimal constructor */
	public BaseClPublicoConsultaDetalle(Integer consultaDetalleId,
			ClConsultaPublico clPublicoConsulta) {
		this.consultaDetalleId = consultaDetalleId;
		this.clPublicoConsulta = clPublicoConsulta;
	}

	/** full constructor */
	public BaseClPublicoConsultaDetalle(Integer consultaDetalleId,
			ClConsultaPublico clPublicoConsulta, String observacion, Date fecha) {
		this.consultaDetalleId = consultaDetalleId;
		this.clPublicoConsulta = clPublicoConsulta;
		this.observacion = observacion;
		this.fecha = fecha;
	}

	// Property accessors

	public Integer getConsultaDetalleId() {
		return this.consultaDetalleId;
	}

	public void setConsultaDetalleId(Integer consultaDetalleId) {
		this.consultaDetalleId = consultaDetalleId;
	}

	public ClConsultaPublico getClPublicoConsulta() {
		return this.clPublicoConsulta;
	}

	public void setClPublicoConsulta(ClConsultaPublico clPublicoConsulta) {
		this.clPublicoConsulta = clPublicoConsulta;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

}