package net.uch.mapping;

// Generated by MyEclipse Persistence Tools
import java.util.Set;
import net.uch.mapping.base.BaseClArbolAcademico;

/**
 * ClArbolAcademico generated by MyEclipse Persistence Tools
 */
public class ClArbolAcademico extends BaseClArbolAcademico implements
        java.io.Serializable {

    // Constructors
    /** default constructor */
    public ClArbolAcademico () {
    }

    /** minimal constructor */
    public ClArbolAcademico ( Integer arbId ) {
        super( arbId );
    }

    /** full constructor */
    public ClArbolAcademico ( Integer arbId, ClArbolAcademico clArbolAcademico,
            String arbOpcion, String arbCodigo, String arbDescripcion,
            String arbTipo, Integer arbNivel, String arbActivo,
            Integer arbIdPadre, String arbFlag, String talNumero, Integer arbIdbak,
            String arbInstitucion, Integer arbVisible, Set clSeccions, Set clArbolAcademicos ) {
        super( arbId, clArbolAcademico, arbOpcion, arbCodigo, arbDescripcion,
                arbTipo, arbNivel, arbActivo, arbIdPadre, arbFlag, arbIdbak, talNumero,
                arbInstitucion, arbVisible,
                clSeccions, clArbolAcademicos );
    }
}
