package net.uch.mapping.base;

import java.util.HashSet;
import java.util.Set;
import net.uch.mapping.AdAreaInstitucion;
import net.uch.mapping.TsResponsable;

/**
 * AbstractTsSolicitud generated by MyEclipse Persistence Tools
 */

public abstract class BaseTsSolicitud implements java.io.Serializable {

	// Fields

	private Integer solId;
	private AdAreaInstitucion adAreaInstitucion;
        private TsResponsable tsResponsable= new TsResponsable();
	private String solCodigo;
	private String solDescripcion;
	private String solTipo;
	private String solActivo;
	private Set tsSolicitudPersonas = new HashSet(0);
	private Set tsRequisitoSolicituds = new HashSet(0);

	// Constructors

	/** default constructor */
	public BaseTsSolicitud() {
	}

	/** minimal constructor */
	public BaseTsSolicitud(Integer solId) {
		this.solId = solId;
	}

	/** full constructor */
	public BaseTsSolicitud(Integer solId,AdAreaInstitucion adAreaInstitucion, 
                        TsResponsable tsResponsable, String solCodigo,
			String solDescripcion, String solTipo, String solActivo,
			Set tsSolicitudPersonas, Set tsRequisitoSolicituds) {
		this.solId = solId;
		this.adAreaInstitucion = adAreaInstitucion;
                this.tsResponsable=tsResponsable;
		this.solCodigo = solCodigo;
		this.solDescripcion = solDescripcion;
		this.solTipo = solTipo;
		this.solActivo = solActivo;
		this.tsSolicitudPersonas = tsSolicitudPersonas;
		this.tsRequisitoSolicituds = tsRequisitoSolicituds;
	}

	// Property accessors

	public Integer getSolId() {
		return this.solId;
	}

	public void setSolId(Integer solId) {
		this.solId = solId;
	}

	public AdAreaInstitucion getAdAreaInstitucion() {
		return this.adAreaInstitucion;
	}

	public void setAdAreaInstitucion(AdAreaInstitucion adAreaInstitucion) {
		this.adAreaInstitucion = adAreaInstitucion;
	}

	public String getSolCodigo() {
		return this.solCodigo;
	}

	public void setSolCodigo(String solCodigo) {
		this.solCodigo = solCodigo;
	}

	public String getSolDescripcion() {
		return this.solDescripcion;
	}

	public void setSolDescripcion(String solDescripcion) {
		this.solDescripcion = solDescripcion;
	}

	public String getSolTipo() {
		return this.solTipo;
	}

	public void setSolTipo(String solTipo) {
		this.solTipo = solTipo;
	}

	public String getSolActivo() {
		return this.solActivo;
	}

	public void setSolActivo(String solActivo) {
		this.solActivo = solActivo;
	}

	public Set getTsSolicitudPersonas() {
		return this.tsSolicitudPersonas;
	}

	public void setTsSolicitudPersonas(Set tsSolicitudPersonas) {
		this.tsSolicitudPersonas = tsSolicitudPersonas;
	}

	public Set getTsRequisitoSolicituds() {
		return this.tsRequisitoSolicituds;
	}

	public void setTsRequisitoSolicituds(Set tsRequisitoSolicituds) {
		this.tsRequisitoSolicituds = tsRequisitoSolicituds;
	}

    public TsResponsable getTsResponsable() {
        return tsResponsable;
    }

    public void setTsResponsable(TsResponsable tsResponsable) {
        this.tsResponsable = tsResponsable;
    }
        
        

}