package net.uch.mapping.base;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import net.uch.mapping.ClAlumno;
import net.uch.mapping.ClArbolAcademico;

/**
 * AbstractClPublicoConsulta generated by MyEclipse Persistence Tools
 */

public abstract class BaseClPublicoConsulta implements java.io.Serializable {

	// Fields

	private Integer consultaId;
	private ClAlumno clAlumno;
	private String area;
	private String tipoArea;
	private Integer diasEstudio;
	private String horarios;
	private Integer publicidad;
	private String detalleMedio;
	private Date fechaContacto;
	private String hora;
	private Integer consultado;
	private Integer matriculado;
	private Integer usuCod;
	private Date fechaRegistro;
	private Date horaRegistro;
	private String obsConsulta;
	private String procedencia;
	private Integer publiDet;
	private Integer sede;
        private ClArbolAcademico clArbolAcademico;
	private Set clPublicoConsultaDetalles = new HashSet(0);

	// Constructors

	/** default constructor */
	public BaseClPublicoConsulta() {
	}

	/** minimal constructor */
	public BaseClPublicoConsulta(Integer consultaId) {
		this.consultaId = consultaId;
	}

	/** full constructor */
	public BaseClPublicoConsulta(Integer consultaId, ClAlumno clAlumno,
			String area, String tipoArea, Integer diasEstudio, String horarios,
			Integer publicidad, String detalleMedio, Date fechaContacto,
			String hora, Integer consultado, Integer matriculado,
			Integer usuCod, Date fechaRegistro, Date horaRegistro,
			String obsConsulta, String procedencia, Integer publiDet,
			Integer sede, Set clPublicoConsultaDetalles, ClArbolAcademico clArbolAcademico) {
		this.consultaId = consultaId;
		this.clAlumno = clAlumno;
		this.area = area;
		this.tipoArea = tipoArea;
		this.diasEstudio = diasEstudio;
		this.horarios = horarios;
		this.publicidad = publicidad;
		this.detalleMedio = detalleMedio;
		this.fechaContacto = fechaContacto;
		this.hora = hora;
		this.consultado = consultado;
		this.matriculado = matriculado;
		this.usuCod = usuCod;
		this.fechaRegistro = fechaRegistro;
		this.horaRegistro = horaRegistro;
		this.obsConsulta = obsConsulta;
		this.procedencia = procedencia;
		this.publiDet = publiDet;
		this.sede = sede;
                this.clArbolAcademico = clArbolAcademico;
		this.clPublicoConsultaDetalles = clPublicoConsultaDetalles;
	}

	// Property accessors

	public Integer getConsultaId() {
		return this.consultaId;
	}

	public void setConsultaId(Integer consultaId) {
		this.consultaId = consultaId;
	}

	public ClAlumno getClAlumno() {
		return this.clAlumno;
	}

	public void setClAlumno(ClAlumno clAlumno) {
		this.clAlumno = clAlumno;
	}

	public String getArea() {
		return this.area;
	}

	public void setArea(String area) {
		this.area = area;
	}

	public String getTipoArea() {
		return this.tipoArea;
	}

	public void setTipoArea(String tipoArea) {
		this.tipoArea = tipoArea;
	}

	public Integer getDiasEstudio() {
		return this.diasEstudio;
	}

	public void setDiasEstudio(Integer diasEstudio) {
		this.diasEstudio = diasEstudio;
	}

	public String getHorarios() {
		return this.horarios;
	}

	public void setHorarios(String horarios) {
		this.horarios = horarios;
	}

	public Integer getPublicidad() {
		return this.publicidad;
	}

	public void setPublicidad(Integer publicidad) {
		this.publicidad = publicidad;
	}

	public String getDetalleMedio() {
		return this.detalleMedio;
	}

	public void setDetalleMedio(String detalleMedio) {
		this.detalleMedio = detalleMedio;
	}

	public Date getFechaContacto() {
		return this.fechaContacto;
	}

	public void setFechaContacto(Date fechaContacto) {
		this.fechaContacto = fechaContacto;
	}

	public String getHora() {
		return this.hora;
	}

	public void setHora(String hora) {
		this.hora = hora;
	}

	public Integer getConsultado() {
		return this.consultado;
	}

	public void setConsultado(Integer consultado) {
		this.consultado = consultado;
	}

	public Integer getMatriculado() {
		return this.matriculado;
	}

	public void setMatriculado(Integer matriculado) {
		this.matriculado = matriculado;
	}

	public Integer getUsuCod() {
		return this.usuCod;
	}

	public void setUsuCod(Integer usuCod) {
		this.usuCod = usuCod;
	}

	public Date getFechaRegistro() {
		return this.fechaRegistro;
	}

	public void setFechaRegistro(Date fechaRegistro) {
		this.fechaRegistro = fechaRegistro;
	}

	public Date getHoraRegistro() {
		return this.horaRegistro;
	}

	public void setHoraRegistro(Date horaRegistro) {
		this.horaRegistro = horaRegistro;
	}

	public String getObsConsulta() {
		return this.obsConsulta;
	}

	public void setObsConsulta(String obsConsulta) {
		this.obsConsulta = obsConsulta;
	}

	public String getProcedencia() {
		return this.procedencia;
	}

	public void setProcedencia(String procedencia) {
		this.procedencia = procedencia;
	}

	public Integer getPubliDet() {
		return this.publiDet;
	}

	public void setPubliDet(Integer publiDet) {
		this.publiDet = publiDet;
	}

	public Integer getSede() {
		return this.sede;
	}

	public void setSede(Integer sede) {
		this.sede = sede;
	}

	public Set getClPublicoConsultaDetalles() {
		return this.clPublicoConsultaDetalles;
	}

	public void setClPublicoConsultaDetalles(Set clPublicoConsultaDetalles) {
		this.clPublicoConsultaDetalles = clPublicoConsultaDetalles;
	}

    /**
     * @return the clArbolAcademico
     */
    public ClArbolAcademico getClArbolAcademico() {
        return this.clArbolAcademico;
    }

    /**
     * @param clArbolAcademico the clArbolAcademico to set
     */
    public void setClArbolAcademico(ClArbolAcademico clArbolAcademico) {
        this.clArbolAcademico = clArbolAcademico;
    }

}