package net.uch.mapping.base;

import net.uch.mapping.TsSolicitudPersona;

/**
 * AbstractTsFut generated by MyEclipse Persistence Tools
 */

public abstract class BaseTsFut implements java.io.Serializable{

	// Fields

	private Integer futId;
	private TsSolicitudPersona tsSolicitudPersona;
	private String futSolicito;
	private String futDirigido;
	private String futCiclo;
	private String futTurno;
	private String futEmail;
	private String futExpongo;
	private String futActivo;
	private String futDia;
	private String futMes;
	private String futAnio;

	// Constructors

	/** default constructor */
	public BaseTsFut() {
	}

	/** minimal constructor */
	public BaseTsFut(Integer futId) {
		this.futId = futId;
	}

	/** full constructor */
	public BaseTsFut(Integer futId, TsSolicitudPersona tsSolicitudPersona,
			String futSolicito, String futDirigido, String futCiclo,
			String futTurno, String futEmail, String futExpongo,
			String futActivo, String futDia, String futMes, String futAnio) {
		this.futId = futId;
		this.tsSolicitudPersona = tsSolicitudPersona;
		this.futSolicito = futSolicito;
		this.futDirigido = futDirigido;
		this.futCiclo = futCiclo;
		this.futTurno = futTurno;
		this.futEmail = futEmail;
		this.futExpongo = futExpongo;
		this.futActivo = futActivo;
		this.futDia = futDia;
		this.futMes = futMes;
		this.futAnio = futAnio;
	}

	// Property accessors

	public Integer getFutId() {
		return this.futId;
	}

	public void setFutId(Integer futId) {
		this.futId = futId;
	}

	public TsSolicitudPersona getTsSolicitudPersona() {
		return this.tsSolicitudPersona;
	}

	public void setTsSolicitudPersona(TsSolicitudPersona tsSolicitudPersona) {
		this.tsSolicitudPersona = tsSolicitudPersona;
	}

	public String getFutSolicito() {
		return this.futSolicito;
	}

	public void setFutSolicito(String futSolicito) {
		this.futSolicito = futSolicito;
	}

	public String getFutDirigido() {
		return this.futDirigido;
	}

	public void setFutDirigido(String futDirigido) {
		this.futDirigido = futDirigido;
	}

	public String getFutCiclo() {
		return this.futCiclo;
	}

	public void setFutCiclo(String futCiclo) {
		this.futCiclo = futCiclo;
	}

	public String getFutTurno() {
		return this.futTurno;
	}

	public void setFutTurno(String futTurno) {
		this.futTurno = futTurno;
	}

	public String getFutEmail() {
		return this.futEmail;
	}

	public void setFutEmail(String futEmail) {
		this.futEmail = futEmail;
	}

	public String getFutExpongo() {
		return this.futExpongo;
	}

	public void setFutExpongo(String futExpongo) {
		this.futExpongo = futExpongo;
	}

	public String getFutActivo() {
		return this.futActivo;
	}

	public void setFutActivo(String futActivo) {
		this.futActivo = futActivo;
	}

	public String getFutDia() {
		return this.futDia;
	}

	public void setFutDia(String futDia) {
		this.futDia = futDia;
	}

	public String getFutMes() {
		return this.futMes;
	}

	public void setFutMes(String futMes) {
		this.futMes = futMes;
	}

	public String getFutAnio() {
		return this.futAnio;
	}

	public void setFutAnio(String futAnio) {
		this.futAnio = futAnio;
	}

}