package net.uch.mapping.base;

import java.util.HashSet;
import java.util.Set;
import net.uch.mapping.ClArbolAcademico;
import net.uch.util.CommonDAO;

/**
 * BaseClArbolAcademico generated by MyEclipse Persistence Tools
 */
public abstract class BaseClArbolAcademico implements java.io.Serializable {

    // Fields
    private Integer m_iArbId;
    private ClArbolAcademico m_clArbolAcademico;
    private String m_sArbOpcion;
    private String m_sArbCodigo;
    private String m_sArbDescripcion;
    private String m_sArbTipo;
    private Integer m_iArbNivel;
    private String m_sArbActivo;
    private Integer m_iArbIdPadre;
    private String m_sArbFlag;
    private Integer m_iArbIdbak;
    private String m_sTalNumero;
    private String m_sArbInstitucion;
    private Integer m_iArbVisible;//Si se muestra en Módulo de Informes -> 0:Oculto / 1:Visible
    private Integer m_iArbVisibleArbol;//Si se muestra en Arbol -> 0:Oculto / 1:Visible
    private String m_sArbAreaModular;
    private Set m_clSeccions = new HashSet( 0 );
    private Set m_clArbolAcademicos = new HashSet( 0 );
    private ClArbolAcademico m_clArbAcadPadre;//Atributo no mapeado

    // Constructors
    /**
     * default constructor
     */
    public BaseClArbolAcademico() {
    }

    /**
     * minimal constructor
     */
    public BaseClArbolAcademico( Integer arbId ) {
        this.m_iArbId = arbId;
    }

    /**
     * full constructor
     */
    public BaseClArbolAcademico( Integer arbId,
            ClArbolAcademico clArbolAcademico, String arbOpcion,
            String arbCodigo, String arbDescripcion, String arbTipo,
            Integer arbNivel, String arbActivo, Integer arbIdPadre,
            String arbFlag, Integer arbIdbak, String talNumero, String arbInstitucion, Integer arbVisible, Set clSeccions,
            Set clArbolAcademicos ) {
        this.m_iArbId = arbId;
        this.m_clArbolAcademico = clArbolAcademico;
        this.m_sArbOpcion = arbOpcion;
        this.m_sArbCodigo = arbCodigo;
        this.m_sArbDescripcion = arbDescripcion;
        this.m_sArbTipo = arbTipo;
        this.m_iArbNivel = arbNivel;
        this.m_sArbActivo = arbActivo;
        this.m_iArbIdPadre = arbIdPadre;
        this.m_sArbFlag = arbFlag;
        this.m_iArbIdbak = arbIdbak;
        this.m_sTalNumero = talNumero;
        this.m_sArbInstitucion = arbInstitucion;
        this.m_iArbVisible = arbVisible;
        this.m_clSeccions = clSeccions;
        this.m_clArbolAcademicos = clArbolAcademicos;
    }

    // Property accessors
    public Integer getArbVisible() {
        return m_iArbVisible;
    }

    public void setArbVisible( Integer arbVisible ) {
        this.m_iArbVisible = arbVisible;
    }
    public Integer getArbVisibleArbol() {
        m_iArbVisibleArbol = m_iArbVisibleArbol == null ? 1 : m_iArbVisibleArbol;
        return m_iArbVisibleArbol;
    }

    public void setArbVisibleArbol( Integer arbVisibleArbol ) {
        this.m_iArbVisibleArbol = arbVisibleArbol;
    }

    public String getArbAreaModular() {
        m_sArbAreaModular = m_sArbAreaModular == null ? "0" : m_sArbAreaModular;
        return m_sArbAreaModular;
    }

    public void setArbAreaModular( String arbAreaModular ) {
        this.m_sArbAreaModular = arbAreaModular;
    }

    public String getArbInstitucion() {
        return m_sArbInstitucion;
    }

    public void setArbInstitucion( String arbInstitucion ) {
        this.m_sArbInstitucion = arbInstitucion;
    }

    public String getTalNumero() {
        return m_sTalNumero;
    }

    public void setTalNumero( String talNumero ) {
        this.m_sTalNumero = talNumero;
    }

    public Integer getArbId() {
        return this.m_iArbId;
    }

    public void setArbId( Integer arbId ) {
        this.m_iArbId = arbId;
    }

    public ClArbolAcademico getClArbolAcademico() {
        return this.m_clArbolAcademico;
    }

    public void setClArbolAcademico( ClArbolAcademico clArbolAcademico ) {
        this.m_clArbolAcademico = clArbolAcademico;
    }

    public String getArbOpcion() {
        return this.m_sArbOpcion;
    }

    public void setArbOpcion( String arbOpcion ) {
        this.m_sArbOpcion = arbOpcion;
    }

    public String getArbCodigo() {
        return this.m_sArbCodigo;
    }

    public void setArbCodigo( String arbCodigo ) {
        this.m_sArbCodigo = arbCodigo;
    }

    public String getArbDescripcion() {
        return this.m_sArbDescripcion;
    }

    public void setArbDescripcion( String arbDescripcion ) {
        this.m_sArbDescripcion = arbDescripcion;
    }

    public String getArbTipo() {
        return this.m_sArbTipo;
    }

    public void setArbTipo( String arbTipo ) {
        this.m_sArbTipo = arbTipo;
    }

    public Integer getArbNivel() {
        return this.m_iArbNivel;
    }

    public void setArbNivel( Integer arbNivel ) {
        this.m_iArbNivel = arbNivel;
    }

    public String getArbActivo() {
        return this.m_sArbActivo;
    }

    public void setArbActivo( String arbActivo ) {
        this.m_sArbActivo = arbActivo;
    }

    public Integer getArbIdPadre() {
        return this.m_iArbIdPadre;
    }

    public void setArbIdPadre( Integer arbIdPadre ) {
        this.m_iArbIdPadre = arbIdPadre;
    }

    public String getArbFlag() {
        return this.m_sArbFlag;
    }

    public void setArbFlag( String arbFlag ) {
        this.m_sArbFlag = arbFlag;
    }

    public Integer getArbIdbak() {
        return this.m_iArbIdbak;
    }

    public void setArbIdbak( Integer arbIdbak ) {
        this.m_iArbIdbak = arbIdbak;
    }

    public Set getClSeccions() {
        return this.m_clSeccions;
    }

    public void setClSeccions( Set clSeccions ) {
        this.m_clSeccions = clSeccions;
    }

    public Set getClArbolAcademicos() {
        return this.m_clArbolAcademicos;
    }

    public void setClArbolAcademicos( Set clArbolAcademicos ) {
        this.m_clArbolAcademicos = clArbolAcademicos;
    }

    public ClArbolAcademico getArbAcadPadre() {
        ClArbolAcademico clArbPadre;
        try {
            clArbPadre = CommonDAO.getClArbolAcademicoDAO().buscarArbolPorId( m_iArbIdPadre );
        } catch ( Exception ex ) {
            clArbPadre = null;
        }
        return clArbPadre;
    }
}