package net.uch.mapping.base;

import net.uch.mapping.TbMenu;
import net.uch.mapping.TbRoles;

/**
 * AbstractTbMenuRol generated by MyEclipse Persistence Tools
 */

public abstract class BaseTbMenuRol implements java.io.Serializable {

	// Fields

	private Integer menrolId;
	private TbMenu tbMenu;
	private TbRoles tbRoles;
	private String menrolActivo;

	// Constructors

	/** default constructor */
	public BaseTbMenuRol() {
	}

	/** minimal constructor */
	public BaseTbMenuRol(Integer menrolId, TbMenu tbMenu, TbRoles tbRoles) {
		this.menrolId = menrolId;
		this.tbMenu = tbMenu;
		this.tbRoles = tbRoles;
	}

	/** full constructor */
	public BaseTbMenuRol(Integer menrolId, TbMenu tbMenu, TbRoles tbRoles,
			String menrolActivo) {
		this.menrolId = menrolId;
		this.tbMenu = tbMenu;
		this.tbRoles = tbRoles;
		this.menrolActivo = menrolActivo;
	}

	// Property accessors

	public Integer getMenrolId() {
		return this.menrolId;
	}

	public void setMenrolId(Integer menrolId) {
		this.menrolId = menrolId;
	}

	public TbMenu getTbMenu() {
		return this.tbMenu;
	}

	public void setTbMenu(TbMenu tbMenu) {
		this.tbMenu = tbMenu;
	}

	public TbRoles getTbRoles() {
		return this.tbRoles;
	}

	public void setTbRoles(TbRoles tbRoles) {
		this.tbRoles = tbRoles;
	}

	public String getMenrolActivo() {
		return this.menrolActivo;
	}

	public void setMenrolActivo(String menrolActivo) {
		this.menrolActivo = menrolActivo;
	}

}