package net.uch.mapping.base;

/**
 * AbstractTsResponsable generated by MyEclipse Persistence Tools
 */

public abstract class BaseTsResponsable implements java.io.Serializable {

	// Fields

	private Integer respId;
	private String respCodigo;
	private String respPaterno;
	private String respMaterno;
	private String respNombre;
	private String respActivo;

	// Constructors

	/** default constructor */
	public BaseTsResponsable() {
	}

	/** full constructor */
	public BaseTsResponsable(String respCodigo, String respPaterno,
			String respMaterno, String respNombre, String respActivo) {
		this.respCodigo = respCodigo;
		this.respPaterno = respPaterno;
		this.respMaterno = respMaterno;
		this.respNombre = respNombre;
		this.respActivo = respActivo;
	}

	// Property accessors

	public Integer getRespId() {
		return this.respId;
	}

	public void setRespId(Integer respId) {
		this.respId = respId;
	}

	public String getRespCodigo() {
		return this.respCodigo;
	}

	public void setRespCodigo(String respCodigo) {
		this.respCodigo = respCodigo;
	}

	public String getRespPaterno() {
		return this.respPaterno;
	}

	public void setRespPaterno(String respPaterno) {
		this.respPaterno = respPaterno;
	}

	public String getRespMaterno() {
		return this.respMaterno;
	}

	public void setRespMaterno(String respMaterno) {
		this.respMaterno = respMaterno;
	}

	public String getRespNombre() {
		return this.respNombre;
	}

	public void setRespNombre(String respNombre) {
		this.respNombre = respNombre;
	}

	public String getRespActivo() {
		return this.respActivo;
	}

	public void setRespActivo(String respActivo) {
		this.respActivo = respActivo;
	}

}