package net.uch.mapping.base;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import net.uch.mapping.ClArbolAcademico;
import net.uch.mapping.ClArbolAperturado;
import net.uch.mapping.ClSeccionGrupo;

/**
 * AbstractClSeccion generated by MyEclipse Persistence Tools
 */
public abstract class BaseClSeccion implements java.io.Serializable {

    // Fields
    private Integer secId;
    private ClArbolAcademico clArbolAcademico;
    private ClArbolAperturado clArbolAperturado;
    private String secCodigo;
    private String secNombre;
    private Integer secVacMin;
    private Integer secVacMax;
    private Integer secTipo;
    private Integer secIdContinuacion;
    private String secTurno;
    private String secActivo;
    private String secObsProrroga;
    private Date secFinicio;
    private Date secFfin;
    private Date secFinicioMatricula;
    private Date secFfinMatricula;
    private Date secFProrroga;
    private Date secFCreacion;
    private Integer locId;
    private Integer plaId;
    private Integer secIdPadre;
    private Integer secIdAsig;
    private Set clNotas = new HashSet( 0 );
    private Set clMatriculaTallers = new HashSet( 0 );
    private Set clHorarias = new HashSet( 0 );
    private ClSeccionGrupo m_clSecGrup;

    public ClSeccionGrupo getClSecGrup() {
        return m_clSecGrup;
    }

    public void setClSecGrup( ClSeccionGrupo clSecGrupd ) {
        m_clSecGrup = clSecGrupd;
    }

    // Constructors
    /**
     * default constructor
     */
    public BaseClSeccion() {
    }

    /**
     * minimal constructor
     */
    public BaseClSeccion( Integer secId ) {
        this.secId = secId;
    }

    /**
     * full constructor
     */
    public BaseClSeccion( Integer secId, ClArbolAcademico clArbolAcademico,
            ClArbolAperturado clArbolAperturado, String secCodigo, String secNombre,
            Integer secVacMin, Integer secVacMax, Integer secTipo, Integer secIdContinuacion, String secTurno,
            String secActivo, Date secFinicio, Date secFfin,
            Date secFinicioMatricula, Date secFfinMatricula, Integer locId,
            Integer plaId, Set clNotas, Set clMatriculaTallers, Set clHorarias,Date secFProrroga, String secObsProrroga,Date secFCreacion, Integer secIdPadre, Integer secIdAsig) {
        this.secId = secId;
        this.clArbolAcademico = clArbolAcademico;
        this.clArbolAperturado = clArbolAperturado;
        this.secCodigo = secCodigo;
        this.secNombre = secNombre;
        this.secVacMin = secVacMin;
        this.secVacMax = secVacMax;
        this.secTipo = secTipo;
        this.secIdContinuacion = secIdContinuacion;
        this.secTurno = secTurno;
        this.secActivo = secActivo;
        this.secFinicio = secFinicio;
        this.secFfin = secFfin;
        this.secFinicioMatricula = secFinicioMatricula;
        this.secFfinMatricula = secFfinMatricula;
        this.locId = locId;
        this.plaId = plaId;
        this.clNotas = clNotas;
        this.clMatriculaTallers = clMatriculaTallers;
        this.clHorarias = clHorarias;
        this.secFProrroga= secFProrroga;
        this.secObsProrroga=secObsProrroga;
        this.secFCreacion=secFCreacion;
        this.secIdPadre=secIdPadre;
        this.secIdAsig=secIdAsig;
    }

    // Property accessors
    public ClArbolAperturado getClArbolAperturado() {
        return clArbolAperturado;
    }

    public void setClArbolAperturado( ClArbolAperturado clArbolAperturado ) {
        this.clArbolAperturado = clArbolAperturado;
    }

    public Integer getSecId() {
        return this.secId;
    }

    public void setSecId( Integer secId ) {
        this.secId = secId;
    }

    public ClArbolAcademico getClArbolAcademico() {
        return this.clArbolAcademico;
    }

    public void setClArbolAcademico( ClArbolAcademico clArbolAcademico ) {
        this.clArbolAcademico = clArbolAcademico;
    }

    public String getSecCodigo() {
        return this.secCodigo;
    }

    public void setSecCodigo( String secCodigo ) {
        this.secCodigo = secCodigo;
    }

    public String getSecNombre() {
        return this.secNombre;
    }

    public void setSecNombre( String secNombre ) {
        this.secNombre = secNombre;
    }

    public Integer getSecVacMin() {
        return this.secVacMin;
    }

    public void setSecVacMin( Integer secVacMin ) {
        this.secVacMin = secVacMin;
    }

    public Integer getSecVacMax() {
        return this.secVacMax;
    }

    public void setSecVacMax( Integer secVacMax ) {
        this.secVacMax = secVacMax;
    }

    public Integer getSecTipo() {
        return secTipo;
    }

    public void setSecTipo( Integer secTipo ) {
        this.secTipo = secTipo;
    }

    public Integer getSecIdContinuacion() {
        return secIdContinuacion;
    }

    public void setSecIdContinuacion( Integer idSecContinuacion ) {
        this.secIdContinuacion = idSecContinuacion;
    }

    public String getSecTurno() {
        return this.secTurno;
    }

    public void setSecTurno( String secTurno ) {
        this.secTurno = secTurno;
    }

    public String getSecActivo() {
        return this.secActivo;
    }

    public void setSecActivo( String secActivo ) {
        this.secActivo = secActivo;
    }

    public Date getSecFinicio() {
        return this.secFinicio;
    }

    public void setSecFinicio( Date secFinicio ) {
        this.secFinicio = secFinicio;
    }

    public Date getSecFfin() {
        return this.secFfin;
    }

    public void setSecFfin( Date secFfin ) {
        this.secFfin = secFfin;
    }

    public Date getSecFinicioMatricula() {
        return this.secFinicioMatricula;
    }

    public void setSecFinicioMatricula( Date secFinicioMatricula ) {
        this.secFinicioMatricula = secFinicioMatricula;
    }

    public Date getSecFfinMatricula() {
        return this.secFfinMatricula;
    }

    public void setSecFfinMatricula( Date secFfinMatricula ) {
        this.secFfinMatricula = secFfinMatricula;
    }

    public Integer getLocId() {
        return this.locId;
    }

    public void setLocId( Integer locId ) {
        this.locId = locId;
    }

    public Integer getPlaId() {
        return this.plaId;
    }

    public void setPlaId( Integer plaId ) {
        this.plaId = plaId;
    }

    public Set getClNotas() {
        return this.clNotas;
    }

    public void setClNotas( Set clNotas ) {
        this.clNotas = clNotas;
    }

    public Set getClMatriculaTallers() {
        return this.clMatriculaTallers;
    }

    public void setClMatriculaTallers( Set clMatriculaTallers ) {
        this.clMatriculaTallers = clMatriculaTallers;
    }

    public Set getClHorarias() {
        return this.clHorarias;
    }

    public void setClHorarias( Set clHorarias ) {
        this.clHorarias = clHorarias;
    }

    public String getSecObsProrroga() {
        return secObsProrroga;
    }

    public void setSecObsProrroga( String secObsProrroga ) {
        this.secObsProrroga = secObsProrroga;
    }

    public Date getSecFProrroga() {
        return secFProrroga;
    }

    public void setSecFProrroga( Date secFProrroga ) {
        this.secFProrroga = secFProrroga;
    }
    
     public Date getSecFCreacion() {
        return secFCreacion;
    }

    public void setSecFCreacion( Date secFCreacion ) {
        this.secFCreacion = secFCreacion;
    }
    
     public Integer getSecIdPadre() {
        return secIdPadre;
    }

    public void setSecIdPadre( Integer secIdPadre ) {
        this.secIdPadre = secIdPadre;
    }

    public Integer getSecIdAsig() {
        return secIdAsig;
    }

    public void setSecIdAsig( Integer secIdAsig ) {
        this.secIdAsig = secIdAsig;
    }
    
}