package net.uch.mapping.base;

import java.util.Date;

/**
 * AbstractClConsultaPublico generated by MyEclipse Persistence Tools
 */
public abstract class BaseClInformacionReferencial implements java.io.Serializable {

    // Fields
    private Integer idReferencial;
    private Integer conId;
    private String personaRecomendar;
    private String correoTelefono;
    private String gradoInstruccion;
    private String ocupacionActual;
    private String activo;
    private Date fechaCreacion;

    // Constructors
    /** default constructor */
    public BaseClInformacionReferencial () {
    }

    public BaseClInformacionReferencial ( Integer idReferencial ) {
        this.idReferencial = idReferencial;
    }

    public BaseClInformacionReferencial(Integer idReferencial, Integer conId, String personaRecomendar, String correoTelefono, String gradoInstruccion, String ocupacionActual, String activo, Date fechaCreacion) {
        this.idReferencial = idReferencial;
        this.conId = conId;
        this.personaRecomendar = personaRecomendar;
        this.correoTelefono = correoTelefono;
        this.gradoInstruccion = gradoInstruccion;
        this.ocupacionActual = ocupacionActual;
        this.activo = activo;
        this.fechaCreacion = fechaCreacion;
    }

    public String getActivo() {
        return activo;
    }

    public void setActivo(String activo) {
        this.activo = activo;
    }

    public Integer getConId() {
        return conId;
    }

    public void setConId(Integer conId) {
        this.conId = conId;
    }

    public String getCorreoTelefono() {
        return correoTelefono;
    }

    public void setCorreoTelefono(String correoTelefono) {
        this.correoTelefono = correoTelefono;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getGradoInstruccion() {
        return gradoInstruccion;
    }

    public void setGradoInstruccion(String gradoInstruccion) {
        this.gradoInstruccion = gradoInstruccion;
    }

    public Integer getIdReferencial() {
        return idReferencial;
    }

    public void setIdReferencial(Integer idReferencial) {
        this.idReferencial = idReferencial;
    }

    public String getOcupacionActual() {
        return ocupacionActual;
    }

    public void setOcupacionActual(String ocupacionActual) {
        this.ocupacionActual = ocupacionActual;
    }

    public String getPersonaRecomendar() {
        return personaRecomendar;
    }

    public void setPersonaRecomendar(String personaRecomendar) {
        this.personaRecomendar = personaRecomendar;
    }

   
}