package net.uch.mapping;

// Generated by MyEclipse Persistence Tools

import net.uch.mapping.base.BaseTbAlumnoFicha;


/**
 * TbAlumnoFicha generated by MyEclipse Persistence Tools
 */
public class TbAlumnoFicha extends BaseTbAlumnoFicha implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public TbAlumnoFicha() {
	}

	/** minimal constructor */
	public TbAlumnoFicha(Integer ficId) {
		super(ficId);
	}

	/** full constructor */
	public TbAlumnoFicha(Integer ficId, Integer aluId, String ficActivo) {
		super(ficId, aluId, ficActivo);
	}

}
