package net.uch.mapping;

// Generated by MyEclipse Persistence Tools

import net.uch.mapping.base.BaseTsRequisitoSolicitud;


/**
 * TsRequisitoSolicitud generated by MyEclipse Persistence Tools
 */
public class TsRequisitoSolicitud extends BaseTsRequisitoSolicitud{

	// Constructors

	/** default constructor */
	public TsRequisitoSolicitud() {
	}

	/** minimal constructor */
	public TsRequisitoSolicitud(Integer reqsolId) {
		super(reqsolId);
	}

	/** full constructor */
	public TsRequisitoSolicitud(Integer reqsolId, TsSolicitud tsSolicitud,
			TsRequisito tsRequisito, String reqsolActivo) {
		super(reqsolId, tsSolicitud, tsRequisito, reqsolActivo);
	}

}
