package net.uch.mapping;

// Generated by MyEclipse Persistence Tools

import net.uch.mapping.base.BaseTsResponsable;


/**
 * TsResponsable generated by MyEclipse Persistence Tools
 */
public class TsResponsable extends BaseTsResponsable implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public TsResponsable() {
	}

	/** full constructor */
	public TsResponsable(String respCodigo, String respPaterno,
			String respMaterno, String respNombre, String respActivo) {
		super(respCodigo, respPaterno, respMaterno, respNombre, respActivo);
	}

}
