package net.uch.mapping;

// Generated by MyEclipse Persistence Tools

import net.uch.mapping.base.BaseClMedioPublicidadDet;


/**
 * ClMedioPublicidadDet generated by MyEclipse Persistence Tools
 */
public class ClMedioPublicidadDet extends BaseClMedioPublicidadDet
		implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public ClMedioPublicidadDet() {
	}

	/** minimal constructor */
	public ClMedioPublicidadDet(Integer idPubDet) {
		super(idPubDet);
	}

	/** full constructor */
	public ClMedioPublicidadDet(Integer idPubDet,
			ClMedioPublicidad clMedioPublicidad, String pubDetDes,
			String pubDetEst, Integer pubDetOrd) {
		super(idPubDet, clMedioPublicidad, pubDetDes, pubDetEst, pubDetOrd);
	}

}
