package net.uch.mapping.base;

import java.util.HashSet;
import java.util.Set;

/**
 * AbstractTsRequisito generated by MyEclipse Persistence Tools
 */

public abstract class BaseTsRequisito implements java.io.Serializable {

	// Fields

	private Integer reqId;
	private String reqCodigo;
	private String reqDescripcion;
	private String reqActivo;
	private String reqCodigoDescriptivo;
	private String reqTipo;
	private String reqProceso;
	private Integer conId;
	private Set tsRequisitoSolicituds = new HashSet(0);

	// Constructors

	/** default constructor */
	public BaseTsRequisito() {
	}

	/** minimal constructor */
	public BaseTsRequisito(Integer reqId) {
		this.reqId = reqId;
	}

	/** full constructor */
	public BaseTsRequisito(Integer reqId, String reqCodigo,
			String reqDescripcion, String reqActivo,
			String reqCodigoDescriptivo, String reqTipo, String reqProceso,
			Integer conId, Set tsRequisitoSolicituds) {
		this.reqId = reqId;
		this.reqCodigo = reqCodigo;
		this.reqDescripcion = reqDescripcion;
		this.reqActivo = reqActivo;
		this.reqCodigoDescriptivo = reqCodigoDescriptivo;
		this.reqTipo = reqTipo;
		this.reqProceso = reqProceso;
		this.conId = conId;
		this.tsRequisitoSolicituds = tsRequisitoSolicituds;
	}

	// Property accessors

	public Integer getReqId() {
		return this.reqId;
	}

	public void setReqId(Integer reqId) {
		this.reqId = reqId;
	}

	public String getReqCodigo() {
		return this.reqCodigo;
	}

	public void setReqCodigo(String reqCodigo) {
		this.reqCodigo = reqCodigo;
	}

	public String getReqDescripcion() {
		return this.reqDescripcion;
	}

	public void setReqDescripcion(String reqDescripcion) {
		this.reqDescripcion = reqDescripcion;
	}

	public String getReqActivo() {
		return this.reqActivo;
	}

	public void setReqActivo(String reqActivo) {
		this.reqActivo = reqActivo;
	}

	public String getReqCodigoDescriptivo() {
		return this.reqCodigoDescriptivo;
	}

	public void setReqCodigoDescriptivo(String reqCodigoDescriptivo) {
		this.reqCodigoDescriptivo = reqCodigoDescriptivo;
	}

	public String getReqTipo() {
		return this.reqTipo;
	}

	public void setReqTipo(String reqTipo) {
		this.reqTipo = reqTipo;
	}

	public String getReqProceso() {
		return this.reqProceso;
	}

	public void setReqProceso(String reqProceso) {
		this.reqProceso = reqProceso;
	}

	public Integer getConId() {
		return this.conId;
	}

	public void setConId(Integer conId) {
		this.conId = conId;
	}

	public Set getTsRequisitoSolicituds() {
		return this.tsRequisitoSolicituds;
	}

	public void setTsRequisitoSolicituds(Set tsRequisitoSolicituds) {
		this.tsRequisitoSolicituds = tsRequisitoSolicituds;
	}

}