package net.uch.mapping.base;

import java.util.HashSet;
import java.util.Set;

/**
 * AbstractClMedioPublicidad generated by MyEclipse Persistence Tools
 */

public abstract class BaseClMedioPublicidad implements java.io.Serializable {

	// Fields

	private Integer idPublicidad;
	private String descripcion;
	private Integer estado;
        private String tipo;
	private Integer orden;
	private Set clMedioPublicidadDets = new HashSet(0);

	// Constructors

	/** default constructor */
	public BaseClMedioPublicidad() {
	}

	/** minimal constructor */
	public BaseClMedioPublicidad(Integer idPublicidad) {
		this.idPublicidad = idPublicidad;
	}

	/** full constructor */
	public BaseClMedioPublicidad(Integer idPublicidad, String descripcion,
			Integer estado,String tipo, Integer orden, Set clMedioPublicidadDets) {
		this.idPublicidad = idPublicidad;
		this.descripcion = descripcion;
		this.estado = estado;
                this.tipo = tipo;
		this.orden = orden;
		this.clMedioPublicidadDets = clMedioPublicidadDets;
	}

	// Property accessors

	public Integer getIdPublicidad() {
		return this.idPublicidad;
	}

	public void setIdPublicidad(Integer idPublicidad) {
		this.idPublicidad = idPublicidad;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Integer getEstado() {
		return this.estado;
	}

	public void setEstado(Integer estado) {
		this.estado = estado;
	}

	public Integer getOrden() {
		return this.orden;
	}
        
        public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setOrden(Integer orden) {
		this.orden = orden;
	}

	public Set getClMedioPublicidadDets() {
		return this.clMedioPublicidadDets;
	}

	public void setClMedioPublicidadDets(Set clMedioPublicidadDets) {
		this.clMedioPublicidadDets = clMedioPublicidadDets;
	}

}