package net.uch.mapping;

// Generated by MyEclipse Persistence Tools

import java.util.Set;
import net.uch.mapping.base.BaseAdAreaInstitucion;

/**
 * AdAreaInstitucion generated by MyEclipse Persistence Tools
 */
public class AdAreaInstitucion extends BaseAdAreaInstitucion implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public AdAreaInstitucion() {
	}

	/** minimal constructor */
	public AdAreaInstitucion(Integer areinsId) {
		super(areinsId);
	}

	/** full constructor */
	public AdAreaInstitucion(Integer areinsId, String areinsCodigo,
			String areinsDescripcion, String areinsTipo, String areinsActivo,
			Set tsSolicituds) {
		super(areinsId, areinsCodigo, areinsDescripcion, areinsTipo,
				areinsActivo, tsSolicituds);
	}

}
