package net.uch.mapping;

// Generated by MyEclipse Persistence Tools

import java.util.Set;
import net.uch.mapping.base.BaseClCurso;

/**
 * ClCurso generated by MyEclipse Persistence Tools
 */
public class ClCurso extends BaseClCurso implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public ClCurso() {
	}

	/** minimal constructor */
	public ClCurso(Integer curId) {
		super(curId);
	}

	/** full constructor */
	public ClCurso(Integer curId, ClModulo clModulo, String curCodigo,
			String curNombre, String curActivo, Set clTallerAperturados) {
		super(curId, clModulo, curCodigo, curNombre, curActivo,
				clTallerAperturados);
	}

}
