package net.uch.mapping;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import net.uch.mapping.base.BaseClNota;

/**
 * ClNota generated by MyEclipse Persistence Tools
 */
public class ClNota extends BaseClNota implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public ClNota() {
	}

	/** minimal constructor */
	public ClNota(Integer notId, ClAlumno clAlumno,
			ClSisEvaPersonalizado clSisEvaPersonalizado) {
		super(notId, clAlumno, clSisEvaPersonalizado);
	}

	/** full constructor */
	public ClNota(Integer notId, ClAlumno clAlumno,
			ClSisEvaPersonalizado clSisEvaPersonalizado, ClSeccion clSeccion,
			Float notNota, String notObservacion, Date notCreacion,
			String notActivo, String notTipo) {
		super(notId, clAlumno, clSisEvaPersonalizado, clSeccion, notNota,
				notObservacion, notCreacion, notActivo, notTipo);
	}

}
