package net.uch.mapping;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import net.uch.mapping.base.BaseClPlantillaHorarioDet;

/**
 * ClPlantillaHorarioDet generated by MyEclipse Persistence Tools
 */
public class ClPlantillaHorarioDet extends BaseClPlantillaHorarioDet
		implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public ClPlantillaHorarioDet() {
	}

	/** minimal constructor */
	public ClPlantillaHorarioDet(Integer pladetId) {
		super(pladetId);
	}

	/** full constructor */
	public ClPlantillaHorarioDet(Integer pladetId,
			ClPlantillaHorario clPlantillaHorario, String pladetDia,
			Date paldetHoraIni, Date pladetHoraFin, String pladetTipo,
			String pladetActivo) {
		super(pladetId, clPlantillaHorario, pladetDia, paldetHoraIni,
				pladetHoraFin, pladetTipo, pladetActivo);
	}

}
