package net.uch.mapping;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import java.util.Set;
import net.uch.mapping.base.BaseClPublicoConsulta;

/**
 * ClPublicoConsulta generated by MyEclipse Persistence Tools
 */
public class ClPublicoConsulta extends BaseClPublicoConsulta implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public ClPublicoConsulta() {
	}

	/** minimal constructor */
	public ClPublicoConsulta(Integer consultaId) {
		super(consultaId);
	}

	/** full constructor */
	public ClPublicoConsulta(Integer consultaId, ClAlumno clAlumno,
			String area, String tipoArea, Integer diasEstudio, String horarios,
			Integer publicidad, String detalleMedio, Date fechaContacto,
			String hora, Integer consultado, Integer matriculado,
			Integer usuCod, Date fechaRegistro, Date horaRegistro,
			String obsConsulta, String procedencia, Integer publiDet,
			Integer sede, Set clPublicoConsultaDetalles, ClArbolAcademico clArbolAcademico) {
		super(consultaId, clAlumno, area, tipoArea, diasEstudio, horarios,
				publicidad, detalleMedio, fechaContacto, hora, consultado,
				matriculado, usuCod, fechaRegistro, horaRegistro, obsConsulta,
				procedencia, publiDet, sede, clPublicoConsultaDetalles, clArbolAcademico);
	}

}
