package net.uch.mapping;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import net.uch.mapping.base.BaseClPublicoConsultaDetalle;

/**
 * ClPublicoConsultaDetalle generated by MyEclipse Persistence Tools
 */
public class ClPublicoConsultaDetalle extends BaseClPublicoConsultaDetalle
		implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public ClPublicoConsultaDetalle() {
	}

	/** minimal constructor */
	public ClPublicoConsultaDetalle(Integer consultaDetalleId,
			ClConsultaPublico clPublicoConsulta) {
		super(consultaDetalleId, clPublicoConsulta);
	}

	/** full constructor */
	public ClPublicoConsultaDetalle(Integer consultaDetalleId,
			ClConsultaPublico clPublicoConsulta, String observacion, Date fecha) {
		super(consultaDetalleId, clPublicoConsulta, observacion, fecha);
	}

}
