package net.uch.mapping;

// Generated by MyEclipse Persistence Tools

import java.util.Set;
import net.uch.mapping.base.BaseClTaller;

/**
 * ClTaller generated by MyEclipse Persistence Tools
 */
public class ClTaller extends BaseClTaller implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public ClTaller() {
	}

	/** minimal constructor */
	public ClTaller(Integer talId, ClPlancurricular clPlancurricular,
			Integer curId) {
		super(talId, clPlancurricular, curId);
	}

	/** full constructor */
	public ClTaller(Integer talId, ClModulo clModulo,
			ClPlancurricular clPlancurricular, String talCodigo,
			String talDescripcion, String talNumero, Integer curId,
			String talActivo, Set clPreRequisitosesForTalIdRequisito,
			Set clPreRequisitosesForTalId, Set clInicios,
			Set clTallerAperturados) {
		super(talId, clModulo, clPlancurricular, talCodigo, talDescripcion,
				talNumero, curId, talActivo,
				clPreRequisitosesForTalIdRequisito, clPreRequisitosesForTalId,
				clInicios, clTallerAperturados);
	}

}
