package net.uch.mapping;

// Generated by MyEclipse Persistence Tools

import net.uch.mapping.base.BaseTbIncidenciaLab;


/**
 * TbIncidenciaLab generated by MyEclipse Persistence Tools
 */
public class TbIncidenciaLab extends BaseTbIncidenciaLab implements
		java.io.Serializable {

	// Constructors

	/** default constructor */
	public TbIncidenciaLab() {
	}
        
        public TbIncidenciaLab(Integer inclabId) {
            super(inclabId);
	}

	/** full constructor */
	public TbIncidenciaLab(AcAlumno acAlumno, String inclabCicloAlu,
			Integer curId, Integer secId,
			String inclabEquipo, String inclabDescripcionDanio,
			String inclabActivo, String inclabEstado,AcTurno acTurno) {
		super(acAlumno, inclabCicloAlu, curId, secId,
				inclabEquipo, inclabDescripcionDanio, inclabActivo,inclabEstado,acTurno);
	}

}
