package net.uch.mapping;
// Generated 14/02/2011 09:37:59 AM by Hibernate Tools 3.2.1.GA



/**
 * TbReporteRol generated by hbm2java
 */
public class TbReporteRol  implements java.io.Serializable {


     private Integer reporRolId;
     private TbRoles tbRoles;
     private TbReporte tbReporte;
     private Character reporRolActivo;
     private Integer usuId;

    public TbReporteRol() {
    }

    public TbReporteRol(TbRoles tbRoles, TbReporte tbReporte, Character reporRolActivo, int usuId) {
       this.tbRoles = tbRoles;
       this.tbReporte = tbReporte;
       this.reporRolActivo = reporRolActivo;
       this.usuId=usuId;
    }
   
    public Integer getReporRolId() {
        return this.reporRolId;
    }
    
    public void setReporRolId(Integer reporRolId) {
        this.reporRolId = reporRolId;
    }
    public TbRoles getTbRoles() {
        return this.tbRoles;
    }
    
    public void setTbRoles(TbRoles tbRoles) {
        this.tbRoles = tbRoles;
    }
    public TbReporte getTbReporte() {
        return this.tbReporte;
    }
    
    public void setTbReporte(TbReporte tbReporte) {
        this.tbReporte = tbReporte;
    }
    public Character getReporRolActivo() {
        return this.reporRolActivo;
    }
    
    public void setReporRolActivo(Character reporRolActivo) {
        this.reporRolActivo = reporRolActivo;
    }

    public Integer getUsuId() {
        return usuId;
    }

    public void setUsuId(Integer usuId) {
        this.usuId = usuId;
    }




}


