package net.uch.mapping;

// Generated by MyEclipse Persistence Tools

import net.uch.mapping.base.BaseTsFut;


/**
 * TsFut generated by MyEclipse Persistence Tools
 */
public class TsFut extends BaseTsFut{

	// Constructors

	/** default constructor */
	public TsFut() {
	}

	/** minimal constructor */
	public TsFut(Integer futId) {
		super(futId);
	}

	/** full constructor */
	public TsFut(Integer futId, TsSolicitudPersona tsSolicitudPersona,
			String futSolicito, String futDirigido, String futCiclo,
			String futTurno, String futEmail, String futExpongo,
			String futActivo, String futDia, String futMes, String futAnio) {
		super(futId, tsSolicitudPersona, futSolicito, futDirigido, futCiclo,
				futTurno, futEmail, futExpongo, futActivo, futDia, futMes,
				futAnio);
	}

}
