package net.uch.mapping;

// Generated by MyEclipse Persistence Tools

import java.util.Set;
import net.uch.mapping.base.BaseTsRequisito;

/**
 * TsRequisito generated by MyEclipse Persistence Tools
 */
public class TsRequisito extends BaseTsRequisito {

	// Constructors

	/** default constructor */
	public TsRequisito() {
	}

	/** minimal constructor */
	public TsRequisito(Integer reqId) {
		super(reqId);
	}

	/** full constructor */
	public TsRequisito(Integer reqId, String reqCodigo, String reqDescripcion,
			String reqActivo, String reqCodigoDescriptivo, String reqTipo,
			String reqProceso, Integer conId, Set tsRequisitoSolicituds) {
		super(reqId, reqCodigo, reqDescripcion, reqActivo,
				reqCodigoDescriptivo, reqTipo, reqProceso, conId,
				tsRequisitoSolicituds);
	}

}
