package net.uch.mapping;

// Generated by MyEclipse Persistence Tools

import java.util.Set;
import net.uch.mapping.base.BaseTsSolicitud;

/**
 * TsSolicitud generated by MyEclipse Persistence Tools
 */
public class TsSolicitud extends BaseTsSolicitud{

	// Constructors

	/** default constructor */
	public TsSolicitud() {
	}

	/** minimal constructor */
	public TsSolicitud(Integer solId) {
		super(solId);
	}

	/** full constructor */
	public TsSolicitud(Integer solId, AdAreaInstitucion adAreaInstitucion,
                        TsResponsable tsResponsable,
			String solCodigo, String solDescripcion, String solTipo,
			String solActivo, Set tsSolicitudPersonas, Set tsRequisitoSolicituds) {
		super(solId, adAreaInstitucion, tsResponsable, solCodigo, solDescripcion, solTipo,
				solActivo, tsSolicitudPersonas, tsRequisitoSolicituds);
	}

}
