package net.uch.mapping;

// Generated by MyEclipse Persistence Tools

import java.util.Date;
import java.util.Set;
import net.uch.mapping.base.BaseClInicio;

/**
 * ClInicio generated by MyEclipse Persistence Tools
 */
public class ClInicio extends BaseClInicio implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public ClInicio() {
	}

	/** minimal constructor */
	public ClInicio(Integer iniId) {
		super(iniId);
	}

	/** full constructor */
	public ClInicio(Integer iniId, ClArbolAcademico clArbolAcademico,
			AcLocal acLocal, String iniCodigo, String iniDescripcion,
			String iniTurno, Date iniFechaInicio, Date iniFechaFin,
			String iniAperturado, String iniActivo, String iniResolucion,
			Integer iniNroHoras, Set clSeccions) {
		super(iniId, clArbolAcademico, acLocal, iniCodigo, iniDescripcion,
				iniTurno, iniFechaInicio, iniFechaFin, iniAperturado,
				iniActivo, iniResolucion, iniNroHoras, clSeccions);
	}

}
